### ISSUE TITLE
Spelling and punctuation errors in the VM's text files

### ISSUE THREAD

**Issue by ynandak** [SoftwareEngineeringToolDemos/ICSE-2011-JDeodorant#10]
There are several errors with spelling, capitalization and grammar in the text files inside the VM, which need to be corrected. A few examples are:

Readme.txt:
- "Virual Machine credentails"
- "Goto"

License.txt:
- "Virtual Box"

All text files:
- Inconsistent capitalization of "Eclipse"

**Comment by YashwanthAsh** [comment]
I made the required changes in the files.
